name: Build Plugins

on: push

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone 
        uses: actions/checkout@v2

      - name: Build 
        run: dotnet publish -c Release src

      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.Modules.zero
          path: src/Artemis.Plugins.Modules.zero/bin/x64/Release/net6.0/publish
