name: Build Plugins

on: push

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone Plugins
        uses: actions/checkout@v2
        with:
          path: Plugins

      - name: Build Plugins
        run: dotnet publish -c Release .\Plugins\src\Artemis.Plugins.zerolass.sln
        
      - name: Upload Artemis.Plugins.Modules.zero
        uses: actions/upload-artifact@v2
        with:
          name: Artemis.Plugins.Modules.zero
          path: .\Plugins\Artemis.Plugins.Modules.zero\bin\x64\Release\net6.0\publish
