name: Build Plugins

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Clone Artemis
        uses: actions/checkout@v3
        with:
          repository: Artemis-RGB/Artemis
          ref: development
          path: Artemis

      - name: Build Artemis Core
        run: dotnet build .\Artemis\src\Artemis.Core\Artemis.Core.csproj
        
      - name: Build Artemis UI Shared
        run: dotnet build .\Artemis\src\Artemis.UI.Shared\Artemis.UI.Shared.csproj

      - name: Build Artemis UI Shared
        run: dotnet build .\Artemis\src\Artemis.UI\Artemis.UI.csproj

      - name: Clone Plugins
        uses: actions/checkout@v3

      - name: Build Plugins
        run: dotnet publish -c Release .\src\Artemis.Plugins.zerolass.sln

      - name: Upload zero
        uses: actions/upload-artifact@v3
        with:
          name: zero
          path: .\Artemis.Plugins.Modules.zero\bin\x64\Release\net6.0\publish
